### ISSUE TITLE
Sub or Dig Area description (SomeInputs B8)

### ISSUE THREAD

**Issue by gojanpaolo** [gldd-se/PostDredge-Public#10]
In hoppers, a `SubJob` will have `DigLocation` and `DischargeLocation`.

For cutters, should we create a `CutterSubJob` model which will have `DigLocation`?
Note that this would mean that a `DigLocation` for a given `CutterSubJob` will never change.

![image](https://user-images.githubusercontent.com/16026608/71053131-22ca4d00-2113-11ea-9e4c-8af7aed21940.png)
*** `SomeInputs` tab

With this, users will have one less user input.

**Comment by rcriii42** [comment]
Hi Jan,

Yes, we can do this. We always have the N/E if we need more.



Robert Ramsdell
Director of Production Engineering and R&D
Great Lakes Dredge & Dock Company
Rcramsdell@gldd.com



-------- Original message --------

**Comment by gojanpaolo** [comment]
@rcriii42 what do you mean by N/E?

**Comment by rcriii42** [comment]
Nothing and easting

**Comment by gojanpaolo** [comment]
Got it! thanks!
