### ISSUE TITLE
Slugger / Hoffer

### ISSUE THREAD

**Issue by gojanpaolo** [gldd-se/PostDredge-Public#11]
- What is a Slugger / Hoffer?
- Are the words Slugger and Hoffer interchangeable/synonymous?
  - If no, what should we name our variable? `SluggerAndHoffer` ?
- Is this applicable to all dredges?
- Is this a fixed value on a given dredge?
  - If no
    - Can this change in the middle of the project? how about subjob?
    - Is this a yes or no input?
  

`SomeInputs` `A15`
![image](https://user-images.githubusercontent.com/16026608/71053450-0da1ee00-2114-11ea-90c7-c4355452684d.png)

**Comment by rcriii42** [comment]
Hi Jan,

This is a suction relief valve that opens if the suction is blocked.  They are the same thing, hoffer (hofer?) Is is better than slugger, but suction relief is best if there is room.



Robert Ramsdell
Director of Production Engineering and R&D
Great Lakes Dredge & Dock Company
Rcramsdell@gldd.com



-------- Original message --------

**Comment by gojanpaolo** [comment]
@rcriii42 would a `HasSuctionReliefValve` make sense since this is a boolean yes/no variable?

**Comment by rcriii42** [comment]
Is this a dredge config parameter? Because in the daily data there should be a hoffer open/close Boolean as well.

Robert

**Comment by gojanpaolo** [comment]
@rcriii42 

> Is this a dredge config parameter?

I am not sure yet. Is this an option that they can apply/remove anytime or will it be fixed on a given dredge e.g. Dredge Carolina `HasSuctionReliefValve` always be `true`?

Also, do all dredges have this option?

**Comment by rcriii42** [comment]
All dredges should have it, but they are often out of service for various reasons.



Robert Ramsdell
Director of Production Engineering and R&D
Great Lakes Dredge & Dock Company
Rcramsdell@gldd.com



-------- Original message --------

**Comment by gojanpaolo** [comment]
Got it! A checkbox will be added to the user inputs for the `HasSuctionReliefValve` variable. Thanks again!

**Comment by gojanpaolo** [comment]
will use `IsSuctionReliefValveWorking` instead of `HasSuctionReliefValve`
