### ISSUE TITLE
Trunion Position (SomeInputs A18) / (CutterPosition A22)

### ISSUE THREAD

**Issue by gojanpaolo** [gldd-se/PostDredge-Public#12]
![image](https://user-images.githubusercontent.com/16026608/71054000-01b72b80-2116-11ea-82de-1dc30525dd7e.png)

- Is this only applicable for Alaska and California?
  - If yes,
    - What is the position for the other dredges?
- Is there a default position for most/all dredges?
  - e.g. if the default position is lowered then we can name the variable `IsTrunionRaised` which will have a default value of `false`

**Comment by rcriii42** [comment]
Correct, only relevant for Alaska ATM. California was scrapped.

Other dredges the default is lower. They may be retrofitted with this in the future.



Robert Ramsdell
Director of Production Engineering and R&D
Great Lakes Dredge & Dock Company
Rcramsdell@gldd.com



-------- Original message --------

**Comment by gojanpaolo** [comment]
@rcriii42 Thank you! we'll name this `IsTrunionRaised` with a default value of `false`. And we'll only show this user input for Dredge Alaska
