### ISSUE TITLE
Can a subjob have multiple dig locations?

### ISSUE THREAD

**Issue by gojanpaolo** [gldd-se/PostDredge-Public#15]
In hoppers, we can define a subjob as a unique combination of one dig location and one disposal location. Is that correct? Because in cutters it looks like a subjob can have many dig locations. e.g. see Project 72584 subjob 341's dig locations are AS2 and AS3.

**Comment by rcriii42** [comment]
I don’t think that is correct, on large projects in particular, subjobs can combine many phases of work.

Robert

**Comment by gojanpaolo** [comment]
Got it! I guess a single subjob can have multiple disposal areas as well?

**Comment by rcriii42** [comment]
Yes
