### ISSUE TITLE
Cutter Dredge Area Slope min/max values

### ISSUE THREAD

**Issue by gojanpaolo** [gldd-se/PostDredge-Public#16]
I think usually the slope is 1:3. But what minimum/maximum value would it make sense to enforce? Currently, I set the min max to be 1 - 3 only so users can enter (1:1, 1:3, 1:2, 2:3, etc). Also, is it possible for the numerator to be higher than the denominator (e.g. 3:1)?

**Comment by rcriii42** [comment]
They can be as flat as 1:5 (rarely more), and rarely <1 (i.e. 0.5 or 2:1). Note that they can also be fractional (2.5:1).

Robert

**Comment by gojanpaolo** [comment]
@rcriii42 thanks for answering my questions. :)

We'll increase the max value to 5, we should be easily be able to increase it in the future.
