### ISSUE TITLE
Cutter Excel stripcharts Discharge Pipeline diameter or length may be incorrect

### ISSUE THREAD

**Issue by gojanpaolo** [gldd-se/PostDredge-Public#17]
The discharge pipeline data is shown in the cutter excel stripcharts CutterPosition worksheet cells AF22 to AL22.

![image](https://user-images.githubusercontent.com/16026608/71561531-5b382800-2a3d-11ea-8be8-8326f485b861.png)

The diameter in AI22 points to SomeInputs B147 `Dredge Pipe`.
But the length in AL22 points to SomeInputs B152 `Suction Length: UWP - M. Pump`.
Shouldn't we use SomeInputs B148 `Dredge Pipe Length` instead? 

![image](https://user-images.githubusercontent.com/16026608/71561543-b5d18400-2a3d-11ea-84ec-7ea133b6d599.png)

**Comment by rcriii42** [comment]
That is correct.

Note suction length is the sum of b151 and b152.



Robert Ramsdell
Director of Production Engineering and R&D
Great Lakes Dredge & Dock Company
Rcramsdell@gldd.com



-------- Original message --------

**Comment by gojanpaolo** [comment]
@rcriii42 which of that is correct? `SomeInputs B152` to be shown in `CutterPosition AL22`?

**Comment by rcriii42** [comment]
I was not clear.

Dredge discharge is b148
Dredge suction is the sum of b152 and b152.



Robert Ramsdell
Director of Production Engineering and R&D
Great Lakes Dredge & Dock Company
Rcramsdell@gldd.com



-------- Original message --------

**Comment by gojanpaolo** [comment]
Got it! I'll take a look how those are used in the calculations and get back if I find something that doesn't make sense. Thanks!

**Comment by rcriii42** [comment]
Hi Jan,

The pipe lengths and diameters for all the dredges are in the Pump4100 database (attached). It is the best source of this data as we keep it up for our calculations. The DB is part of the Pump4100 github repository here:

https://github.com/gldd-se/pump4100/tree/master/database

Robert

**Comment by gojanpaolo** [comment]
@rcriii42 thanks for the link but I currently don't have access to the repository. You could add me as a collaborator to that repository by following this guide: https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/adding-outside-collaborators-to-repositories-in-your-organization
Skip to step 4 once you're in the repository page.

**Comment by gojanpaolo** [comment]
Looked at the pump4100 db
```sql
select pltName, DrgLen, SucLen from plants where pltID = 35
```

Corrected the printed pipe line lengths:

![image](https://user-images.githubusercontent.com/16026608/72124760-7e12e800-332b-11ea-8be1-d69b147f6183.png)
