### ISSUE TITLE
Is `CutterPosition L20` "psi" for compressive strength?

### ISSUE THREAD

**Issue by gojanpaolo** [gldd-se/PostDredge-Public#22]
![image](https://user-images.githubusercontent.com/16026608/71868811-68a48080-30d5-11ea-9ddb-3bed9cfd3d12.png)

**Comment by rcriii42** [comment]
Hi Jan,

Yes. The psi is the compressive strength.
TCR is Total Core Recovery, the length of recovered core divided by the length drilled.
RQD is Rock Quality Designation, the percent of recovered core in solid 10 cm lengths divided by the length drilled.

More detail here: https://bullseye.gldd.com/TeamSites/Production/Wiki/Home.aspx#Rock

Robert

**Comment by gojanpaolo** [comment]
Thank you!
