### ISSUE TITLE
What is knife in pumps? (CutterPosition AA20-24)

### ISSUE THREAD

**Issue by gojanpaolo** [gldd-se/PostDredge-Public#24]
![image](https://user-images.githubusercontent.com/16026608/72029364-50ef0880-324b-11ea-9d00-32bf8dfe27f6.png)

What is knife?

Are these values fixed per dredge? (e.g. Carolina UWP will always be knife?)

As discussed with Marley, knife does not apply for booster pumps (AA23-24)

**Comment by rcriii42** [comment]
A knife is a bar welded into the cleanout, that protrudes into the eye of the pump. It reduces pump stops when digging rock. My theory is that it works by inducing tumbling of the rocks so they are more likely to find a way thought the impeller without getting wedged (i.e. I don’t think it cuts or ‘breaks’ the rocks). It has a detrimental effect on the performance of the pump<https://bullseye.gldd.com/TeamSites/Production/Production%20Memos/Knife%20affects%20on%20Pump%20Developed%20Pressures.pdf>. I’m looking for a picture.

Not fixed, they put it in and take it out depending on the digging.

Yes, knives generally are only in main pumps of dredges.

Robert

**Comment by gojanpaolo** [comment]
> Yes, knives generally are only in main pumps of dredges.

Is the Under Water Pump included when you say main pumps?

For Carolina, we have 2 main pumps (in series?), is it possible for one pump to have knife but one does not?

**Comment by rcriii42** [comment]
Main pump distinct from the UWP. Carolina and Ohio have 2 main pumps.

I think one field for the dredge is fine, rather than trying to track it per pump.

Robert

**Comment by rcriii42** [comment]
[cid:image001.jpg@01D5C6CE.17237520][cid:image002.jpg@01D5C6CE.17237520]

**Comment by gojanpaolo** [comment]
resolved in https://github.com/gldd-se/PostDredge/commit/50695b85ee62181bfcd6ffd603d6f30b75635c62
