### ISSUE TITLE
Missing Booster Pump Power

### ISSUE THREAD

**Issue by gojanpaolo** [gldd-se/PostDredge-Public#26]
What is the pump power of the following boosters?
- Booster # 9
- Florida
- Long Island
- Ohio
- Utah
- Wadmalaw

Other boosters' pump power in SomeInputs I7-J20
![image](https://user-images.githubusercontent.com/16026608/72031857-60724f80-3253-11ea-9225-766ae63b4ca5.png)

**Comment by rcriii42** [comment]
3600, it is identical to Jack, Reggie, Erin, Texas Jr, barney and CR main pumps.

Note we do not need Arizona, NATCO, skid, lighting, CSDPET, or Pontchartrain. We will be adding boosters in the near future.

Robert

**Comment by gojanpaolo** [comment]
> 3600, it is identical to Jack, Reggie, Erin, Texas Jr, barney and CR main pumps.

Just to clarify, is it 3600 for 6 boosters listed below?
- Booster # 9
- Florida
- Long Island
- Ohio
- Utah
- Wadmalaw

**Comment by gojanpaolo** [comment]
> Arizona, NATCO, skid, lighting, CSDPET, or Pontchartrain.  We will be adding boosters in the near future.

Got it. we should be able to easily add boosters :)

Why is Arizona not needed? Currently, users can select Arizona booster when entering Hopper Load in PostDredge.

**Comment by rcriii42** [comment]
Just booster 9, the others really don’t need to be in the list.

Florida, Long Island, Utah no longer exist
Ohio is a dredge
Wadmalaw is now a dredge, belongs to a competitor.

**Comment by rcriii42** [comment]
Arizona was scrapped.

**Comment by gojanpaolo** [comment]
Got it! opened #188 to track removing those boosters
