### ISSUE TITLE
Line length (ProcessData C249) vs Pipeline lengths (Cutter Position AL18-AL28)

### ISSUE THREAD

**Issue by gojanpaolo** [gldd-se/PostDredge-Public#27]
ProcessData C249

![image](https://user-images.githubusercontent.com/16026608/72033139-083d4c80-3257-11ea-840e-df55c345b1b9.png)

---

CutterPosition AL18-AL28

![image](https://user-images.githubusercontent.com/16026608/72033159-17bc9580-3257-11ea-9825-f397017caf81.png)

---

Can we just calculate the Line Length in ProcessData C249 using the inputs for CutterPosition AL18-AL28? If yes, what is the formula? I think it will be just a sum, but which values?

**Comment by rcriii42** [comment]
Yes, but exclude the suction.

The line length here is to calculate the line density. Since the density gauge is generally near the main pump, we want the line after that pump.

Note that this does not match AS400 line length, which excludes the dredge suction and discharge.

Robert

**Comment by gojanpaolo** [comment]
Got it! Thank you!
My task tonight is to add the pipe line length inputs so I'll get back to this issue later.
