### ISSUE TITLE
Calculate DigProductionVolume

### ISSUE THREAD

**Issue by gojanpaolo** [gldd-se/PostDredge-Public#31]
- [x] Add to db CutterAnalysis.CalculatedDigProductionVolume
  - [x] Use this in past production table if SurveyedDigProductionVolume is null or 0
  - [x] Consider using as reference value if referenceInput.SurveyedDigProductionVolume is null or 0
- When calculating density correction factor
  - [x] use surveyed dig production volume
  - [x] else use latest past correction factor
     - [ ] consider limit for valid past correction factor (e.g. 10 days?)
  - [x] else default to 1
- [ ] Consider changing CutterInput.SurveyedDigProductionVolume as nullable
  - so it will show up as empty instead of 0 in UI.

**Comment by rcriii42** [comment]
?This is the value calculated from velocity and density? We should not use this to calculate the correction factor, rather this should be calculated with the past correction factor applied until a survey volume is input. Then the correction factor will be updated and this recalculated to match.


Robert C. Ramsdell III
Production Engineering Manager
Great Lakes Dredge & Dock Company
2122 York Road
Oakbrook, IL 60523
rcramsdell@gldd.com
Phone: 630-574-3463
Mobile: 630-805-1776
Fax: 630-574-2909

________________________________

**Comment by gojanpaolo** [comment]
> We should not use this to calculate the correction factor

Yes, currently we don't use the Calculated Dig Production Volume to calculate the correction factor.

> rather this should be calculated with the past correction factor applied until a survey volume is input

When there is no Surveyed Volume yet, should we use a correction factor of `1` (i.e. won't affect calculation) instead of the past correction factor? I believe the correction factor on each day varies a lot so using `1` may be a safer choice?

**Comment by rcriii42** [comment]
If all is well, the correction factor should be fairly consistent day-to-day, so I'd use the latest correction factor in the calcs absent survey volumes. That is what the current system does.


If the correction factor varies much day-to-day, that implies bad survey volumes.


Robert C. Ramsdell III
Production Engineering Manager
Great Lakes Dredge & Dock Company
2122 York Road
Oakbrook, IL 60523
rcramsdell@gldd.com
Phone: 630-574-3463
Mobile: 630-805-1776
Fax: 630-574-2909

________________________________

**Comment by gojanpaolo** [comment]
Got it! Thanks for your inputs, we should be able to implement this tonight :)

**Comment by gojanpaolo** [comment]
Fixed in https://github.com/gldd-se/PostDredge/commit/a440f176e642b3e241a4c8219c9a90d9e1cc9421
