### ISSUE TITLE
Excel Stripchart Back Swing / Dig Swing values (Hydro CX to DI) seems to be incorrect for Dredges with Stbd Dig Direction

### ISSUE THREAD

**Issue by gojanpaolo** [gldd-se/PostDredge-Public#37]
For example, Carolina Excel Stripcharts Hydro CX6 (DS Prod) formula is

```vb
=IF(I6+360<I2+360,U6,"")
```

where `I` is the heading values

The IF condition will return true if turning towards Port.
The logic is the same for all dredges' excel stripcharts.
But if the dredge dig direction is Stbd (Carolina/Texas), then that logic is incorrect.

Or am I missing something?

**Comment by rcriii42** [comment]
Yes,

The column label is incorrect, it should really be “stbd_prod”, “Port_prod”. For the range columns (BY, BZ), that is how ythey are used, and the label is colored to match the direction, red port, green stbd, in StripCharts:C30.

Robert

**Comment by gojanpaolo** [comment]
Thanks Robert for the confirmation. That would also mean that some of the values for Dig/Back Swing in the Analysis tab are switched for Carolina and Texas.

![image](https://user-images.githubusercontent.com/16026608/72489992-7c3d9e80-37db-11ea-8578-ed3a53736b01.png)

**Comment by rcriii42** [comment]
Not surprised at all.

If we had a swing analyzer, written in python, could you incorporate it? It would count the number of swings and provide statistics.



Robert Ramsdell
Director of Production Engineering and R&D
Great Lakes Dredge & Dock Company
Rcramsdell@gldd.com



-------- Original message --------

**Comment by gojanpaolo** [comment]
Yes I think that's possible. I actually just implemented a logic to get the end/start of the swing to automatically populate the charts with green and red vertical lines. Though I haven't done a lot of testing with that yet.

---

```c#
foreach (var t in
    FindLocalExtremas(analysis.Records
    .Where(r => r.DateTime.TimeOfDay >= period.Start && r.DateTime.TimeOfDay <= period.End)
    .ToList(),
    100))
    chart.GetXYDiagram()!.AxisX.ConstantLines.Add(new ConstantLine
    {
        AxisValue = t.record.DateTime.TimeOfDay,
        Color = t.isMaxima ? Color.Lime : Color.Red,
        ShowInLegend = false
    });
```
https://github.com/gldd-se/PostDredge/blob/1e5679073d2c8011e4a697eed829eebed5116c87/src/Gldd.PostDredge/Cutter/Reporting/DailyCharts.cs#L60-L70

---
```c#
private static IList<(Record record, bool isMaxima)> FindLocalExtremas(IList<Record> values, int rangeOfPeaks)
{
    var peaks = new List<(Record, bool)>();
    Record current;
    IEnumerable<Record> range;

    int checksOnEachSide = rangeOfPeaks / 2;
    for (int i = 0; i < values.Count; i++)
    {
        current = values[i];
        range = values;

        if (i > checksOnEachSide)
        {
            range = range.Skip(i - checksOnEachSide);
        }

        range = range.Take(rangeOfPeaks);
        if (range.Count() > 0)
        {
            if (current.CutterRange == range.Max(r => r.CutterRange))
                peaks.Add((current, true));
            else if (current.CutterRange == range.Min(r => r.CutterRange))
                peaks.Add((current, false));
        }
    }

    return peaks;
}
```
https://github.com/gldd-se/PostDredge/blob/1e5679073d2c8011e4a697eed829eebed5116c87/src/Gldd.PostDredge/Cutter/Reporting/DailyCharts.cs#L136-L164
