### ISSUE TITLE
Update swing calculation

### ISSUE THREAD

**Issue by gojanpaolo** [gldd-se/PostDredge-Public#49]
![image](https://user-images.githubusercontent.com/16026608/77713025-571b9800-6fa3-11ea-8c43-27ed064374cd.png)

![image](https://user-images.githubusercontent.com/16026608/77812045-b72a4100-706c-11ea-89e6-f70aaeaba1ec.png)

**Comment by rcriii42** [comment]
A technique I used in the past was a two-pass filter. On the second pass smaller time periods were aggregated.

Robert

**Comment by gojanpaolo** [comment]
Fixed in https://github.com/gldd-se/PostDredge/commit/ad770de2ca5733581960cfb250ac960a60e38fa6
