### ISSUE TITLE
BD (CutterPosition J15) / Existing Ground (SomeInputs C47)

### ISSUE THREAD

**Issue by gojanpaolo** [gldd-se/PostDredge-Public#9]
Should we calculate the average of the `Surveyed_Depth` in the MDB file instead of a user input?
The value will then go to the following header.

![image](https://user-images.githubusercontent.com/16026608/71052784-11347580-2112-11ea-9b80-6eb881282ad9.png)
*** this is in CutterPosition tab

**Comment by rcriii42** [comment]
?Yes, if the data is there.


Robert C. Ramsdell III
Production Engineering Manager
Great Lakes Dredge & Dock Company
2122 York Road
Oakbrook, IL 60523
rcramsdell@gldd.com
Phone: 630-574-3463
Mobile: 630-805-1776
Fax: 630-574-2909

________________________________

**Comment by gojanpaolo** [comment]
Thanks Robert!
